### ISSUE TITLE
UI  in admin payload 2.0

### ISSUE THREAD

**Issue by MinSomai** [boomworks/payload-plugin-author-fields#11]
As you can see UI is all the way to the left in admin profile page.

<img width="1438" alt="Screenshot 2023-10-14 at 10 09 52 AM" src="https://github.com/boomworks/payload-plugin-author-fields/assets/21338691/915c6749-f26f-46ea-8ee5-578142274b7e">

**Comment by lindsayevans** [comment]
@MinSomai thanks for reporting that - I should be able to take a look sometime this week

**Comment by MinSomai** [comment]
PayloadCMS issue. fixed here. https://github.com/payloadcms/payload/pull/3798
