### ISSUE TITLE
Do not display if its value blank , undefined or no permission 

### ISSUE THREAD

**Issue by ccfiel** [boomworks/payload-plugin-author-fields#20]
It's better not to display if its value is blank, undefined, or without permission. 

<img width="1375" alt="SCR-20231022-pzyx" src="https://github.com/boomworks/payload-plugin-author-fields/assets/1788360/6f050472-b2db-4999-b37d-67b91dc0d99d">

**Comment by lindsayevans** [comment]
@ccfiel have just published v1.1.6 with a fix for this included
