### ISSUE TITLE
args.req.user can be null

### ISSUE THREAD

**Issue by cerize** [boomworks/payload-plugin-author-fields#31]
Hi! When I make a call to the rest api, in some cases the args.req.user is coming as null, which is not a problem per se, but then this plugin tries to read its 'id'. This breaks payload.update().

TypeError: Cannot read properties of null (reading 'id')
    at /node_modules/@boomworks/payload-plugin-author-fields/src/authorHook.ts:19:30

Not sure if it could have any side effects but if we add  a check to the condition below, it solves the issue. Do you think this is something that could be added? I could make a PR if it makes things easier!

From: 

  if (args.operation === 'update' &&
                args.data !== undefined &&
                args.req.user !== undefined)

To: 

  if (args.operation === 'update' &&
                args.data !== undefined &&
                args.req.user !== undefined &&
                args.req.user !== null)

Thank you for your work on this plugin!

**Comment by lindsayevans** [comment]
Hi @cerize  - this should be fixed now in v1.1.9

**Comment by cerize** [comment]
Thanks so much @lindsayevans !!
