### ISSUE TITLE
APIError: Cannot find field for path at _id

### ISSUE THREAD

**Issue by cjrussell23** [boomworks/payload-plugin-author-fields#34]
DisplayOnlyField. is making a request to /api/users?where[_id][equals]=1 which is not working.
I think this is because the query should be /api/users?where[id][equals]=1

This is on line 52 of https://github.com/boomworks/payload-plugin-author-fields/blob/develop/src/DisplayOnlyField/DisplayOnlyField.tsx

`${serverURL}${api}/${relation}?where[_id][equals]=${value.value}`,

**Comment by lindsayevans** [comment]
Hi @cjrussell23  - this should be fixed now in v1.1.9
