### ISSUE TITLE
Plugin seems to break /admin/create-first-user page

### ISSUE THREAD

**Issue by cerize** [boomworks/payload-plugin-author-fields#6]
Hi! I came across this issue and would like to know if it's something you experienced. I was able to reproduce in a freshly created app with npx create-payload-app:
<img width="531" alt="Screen Shot 2023-05-05 at 11 54 03 AM" src="https://user-images.githubusercontent.com/12276027/236562847-f9cf1c43-e259-48af-a1cc-9314b8013bca.png">

**Comment by lindsayevans** [comment]
Hmm, haven't seen that one before.
I'm guessing it's trying to access the user before it exists - hopefully an easy fix

**Comment by lindsayevans** [comment]
@cerize I've just published v1.1.2 to NPM that should fix this issue

**Comment by cerize** [comment]
thanks so much @lindsayevans !
